### ISSUE TITLE
Inserting the non minified file doesn't include the angular module

### ISSUE THREAD

**Issue by epayet** [awendland/angular-json-tree#3] opened 2015-03-26 19:10 UTC
If I insert the minified file (`build/angular-json-tree.min.js`), everything is fine.
I got the "Module 'angular-json-tree' is not available!" when I insert the `build/angular-json-tree.js` file

**Comment by awendland** [comment] 2016-05-24 20:05
How peculiar. The gh-pages demo uses the minified version and it appears to work fine.

**Comment by awendland** [comment] 2016-05-24 20:06
Because I can't reproduce this bug, I am going to close this issue.

**Closed as completed by awendland** 2016-05-24 20:06 UTC
